# Generated by Django 3.0.5 on 2020-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEX3app', '0002_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='tmp_dir_ready_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150, verbose_name='token')),
                ('dir_name', models.CharField(max_length=50, verbose_name='Temp dir for loaded files')),
                ('res_ready', models.BooleanField(default=False, verbose_name='Flag to resualt is ready')),
            ],
        ),
    ]
